import { Component, OnInit, ViewChild } from '@angular/core';
import { MatTable } from '@angular/material/table';

@Component({
  selector: 'app-analytics-view-all-student',
  templateUrl: './analytics-view-all-student.component.html',
  styleUrls: ['./analytics-view-all-student.component.scss']
})
export class AnalyticsViewAllStudentComponent implements OnInit {

  constructor() { }
  studentList: any = [
{
  checkbox: '',
    student_id: '',
    name: '',
    location: '',
    major: '',
    assignedTo: '',
    priority: '',
    status: '',
    placementGroup: '',
    // monthlyCohort: '',
    campus: '',
    resumeLevel: '',
    area: '',
    skills: '',
    docs: '',
    email: '',
    // primaryEmail: '', 
    // secondaryEmail: '', 
    IIS: '',
    ppiDate: '',
    ppiId: '',
    schoolName: '',
    homeCampus: '',
    gender: '',
    dob: '',
    courseCode: '',
    courseName: '',
    coursStartDate: '',
    coursEndDate: '',
    subjectStatus: '',
    nationality: '',
    addressLine1: '',
    suburb: '',
    state: '',
    postcode: '',
    country: '',
    mobile: '',
    tentativeStartDate: '',
    internshipStartDate: '',
    internshipEndDate: '',
    semesterName: '',
    year: '',
    subjectCode: '',
    subjectName: '',
    userName: '',
    vivoMarketingIisPpi: '',
    //  marketing: '', 
    vivoExpiry: '',
    placementType: '',
    notes: '',
    siteVisitDate: '',
    companyName: '',
    ABN: '',
    internshipPositionTitle: '',
    workplaceArrangement: '',
    internshipDays: '',
    hoursWeek: '',
    // totalHours: '', 
    TPAFDeadline: '',
    TPAFReceived: '',
    week1CheckIn: '',
    week1CheckInReceived: '',
    MPR_ECV1_6Deadline: '',
    MPR_ECV1_6Received: '',
    studentMPC_ID: '',
    SUP_MPC_ID: '',
    EPR_ECV7_12Deadline: '',
    EPR_ECV7_12Received: '',
    studentEPC_ID: '',
    SUP_EPC_ID: '',
    actions: '',
}
  ];
  ngOnInit(): void {
  }
  displayColumns: string[] = [
    'checkbox',
    'student_id',
    'name',
    'location',
    'major',
    'assignedTo',
    'priority',
    'status',
    'placementGroup',
    // 'monthlyCohort',
    'campus',
    'resumeLevel',
    'area',
    'skills',
    'docs',
    'email',
    // 'primaryEmail', 
    // 'secondaryEmail', 
    'IIS',
    'ppiDate',
    'ppiId',
    'schoolName',
    'homeCampus',
    'gender',
    'dob',
    'courseCode',
    'courseName',
    'coursStartDate',
    'coursEndDate',
    'subjectStatus',
    'nationality',
    'addressLine1',
    'suburb',
    'state',
    'postcode',
    'country',
    'mobile',
    'tentativeStartDate',
    'internshipStartDate',
    'internshipEndDate',
    'semesterName',
    'year',
    'subjectCode',
    'subjectName',
    'userName',
    'vivoMarketingIisPpi',
    //  'marketing', 
    'vivoExpiry',
    'placementType',
    'notes',
    'siteVisitDate',
    'companyName',
    'ABN',
    'internshipPositionTitle',
    'workplaceArrangement',
    'internshipDays',
    'hoursWeek',
    // 'totalHours', 
    'TPAFDeadline',
    'TPAFReceived',
    'week1CheckIn',
    'week1CheckInReceived',
    'MPR_ECV1_6Deadline',
    'MPR_ECV1_6Received',
    'studentMPC_ID',
    'SUP_MPC_ID',
    'EPR_ECV7_12Deadline',
    'EPR_ECV7_12Received',
    'studentEPC_ID',
    'SUP_EPC_ID',
    'actions',
  ];
  dataSource = this.studentList;
  @ViewChild(MatTable) table: MatTable<any>;

}
